bodhiteam/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sales/',include('sales.urls',namespace='sales')),
    path('api/sales/',include('sales.api.urls')),
    path('',include('membership.urls')),
    path('api/membership/',include('membership.api.urls')),
    path('tech/',include('tech.urls',namespace='tech')),
    path('silk/',include('silk.urls',namespace='silk'))
]

sales/api/urls.py
from django.conf.urls import url
from django.urls import path
from sales.api import views



urlpatterns = [
    url(r'get_my_New_leads/$',views.GetMyNewLeads.as_view(),name='salesExecutiveGetLeads'),
    url(r'get_my_datewise_leads/$',views.GetMyNewLeadsDateWise.as_view(),name='salesExecutiveGetDateWiseLeads'),
    url(r'give_feedback_lead/$',views.GiveLeadFeedBack.as_view(),name='giveLeadFeedBack'),
    url(r'find_type_feedback/$',views.FindTypeFeedBack.as_view(),name='findTypeFeedBack'),
    url(r'get_all_sales_people/$',views.GetAllSalesExecutives.as_view(),name='getAllSalesExecutive'),
    
    url(r'get_my_worked_leads/$', views.GetWorkedLeadsApi.as_view(), name='get_my_all_leads'),
    url(r'get_feedback_or_demos_A_specificLead/$', views.GetFeedbackOrDemos_A_specificLeadWiseApi.as_view(), name='get_specific_feedback_or_demos'),
    url(r'give_demo_feedback/$', views.GiveDemoFeedBackApi.as_view(), name='give_demo_feedback'),
    url(r'Get_MyAssignedLeads/$', views.GetMyAssignedLeadsAPI.as_view(), name='Get_MyAssignedLeads'),
    url(r'Get_specific_lead_andfeedback/$', views.GetSpecificLeadAndFeedbackAPI.as_view(), name='Get_specific_lead_andfeedback'),
    url(r'Send_message_to_user/$', views.SendMessageToUserAPI.as_view(), name='Send_message_to_user'),
    url(r'Get_feedbackes_leadwise_by_ajex/$', views.GetFeedbackesLeadWiseUsingAjexAPI.as_view(), name='Get_feedbackes_leadwise_by_ajex'),
    url(r'Get_my_all_message/$', views.MessagesInboxAPI.as_view(), name='Get_my_all_message'),
    url(r'Get_specific_massages/$', views.GetMySpecificMessageAPI.as_view(), name='Get_specific_massages'),
    url(r'specific_user_notifications/$', views.SpecificUserNotificationsAPI.as_view(), name='specific_user_notifications'),
    url(r'add_successfull_lead/$', views.AddSuccessfullyLeadsAPI.as_view(), name='add_successfull_lead'),
    url(r'get_my_successfully_leads/$', views.SpecificPersonSuccessfullyLeadsAPI.as_view(), name='get_my_successfully_leads'),
    url(r'applyFilterAndSearch/$', views.ApplyFilterAndSeacrhAPI.as_view(), name='applyFilterAndSearch'),
    url(r'applysorting/$', views.SortingApplyAPI.as_view(), name='applysorting'),
    url(r'salesUserProfile/$', views.SalesUserProfileApi.as_view(), name='salesUserProfile'),
    url(r'salesUser_changePassword/$', views.SalesUserChangePasswordApi.as_view(), name='salesUser_changePassword'),
    url(r'filterAndSortForAdmin/$', views.FilterAndSortForAdminApi.as_view(), name='filterAndSortForAdmin'),
    url(r'assignLeadToAnotherUser/$', views.AssignLeadToAnotherUserApi.as_view(), name='assignLeadToAnotherUser'),
    url(r'deleteLead/$', views.DeleteLeadByAdminApi.as_view(), name='deleteLead'),

    url(r'logout/$', views.LogoutUserApi.as_view(), name='logout'),

]

sales/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name = 'sales'

urlpatterns = [
    path('upload_csv',views.lead_upload,name='uploadLoad'),
    path('login',views.loginView,name='login'),
    path('logout',views.logoutview,name='logout'),
    path('Get_my_new_leads',views.GetMyNewLeadView,name='Get_my_all_leads'),
    path('Get_my_worked_leads',views.GetMyWorkedLeadsView,name='Get_my_worked_leads'),
    path('GetFeedbackesAsnDemos_Specificlead_wise/',views.GetFeedbackesAndDemos_A_SpecificLeadWiseView,name='GetMyFeedbackesLeadWise'),
    url(r'feedback_creating/$',views.FeedbackCreateView.as_view(),name='feedback'),
    url(r'demo_creating/$',views.DemoCreatingView.as_view(),name='demo_creating'),
    url(r'Sendmassage/$',views.SendMassageToUserView.as_view(),name='Sendmassage'),
    url(r'add_comfirmLead/$',views.AddSuccessfullyLeadView.as_view(),name='add_comfirmLead'),
    
    url(r'apply_filter_AndSearch/$',views.ApplyFilterAndSeacrhView.as_view(),name='apply_filter_AndSearch'),
    path('applySorting/<slug:sorting_type>/',views.SortingApplyView,name='applySorting'),


    path('getting_feedbackes_leadwise_by_ajex/',views.GetFeedbackesLeadWiseUsingAjexView,name='getting_feedbackes_leadwise_by_ajex'),
    path('messagesInbox/',views.MessagesInboxView,name='messagesInbox'),
    path('Get_specific_user_messages/<int:user_id>/',views.GetSpecificUserMessageView,name='Get_specific_user_messages'),
    path('Get_specific_lead_andfeedback/<int:lead_id>/',views.GetSpecificLeadAndFeedbackView,name='Get_specific_lead_andfeedback'),
    path('Get_specific_lead_andfeedback/<int:lead_id>/<int:feedback_id>/',views.GetSpecificLeadAndFeedbackView,name='Get_specific_lead_andfeedback'),
    path('Get_my_assigned_leads/',views.GetMyAssignedLeadsView,name='Get_my_assigned_leads'),
    path('Get_my_all_notifications/',views.GetMyAllNotificationsView,name='Get_my_all_notifications'),
    path('Specific_person_successfullLeads/',views.SpecificPersonSuccessfullyLeadsView,name='Specific_person_successfullLeads'),
    path('salesUser_profile/',views.SalesUserProfileView,name='salesUser_profile'),
    path('salesUser_changePassword/',views.SalesUserChangePasswordView,name='salesUser_changePassword'),

]

tech/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name = 'tech'

urlpatterns = [
    path('Get_Mynewtask/',views.GetMyNewTaskView,name='Get_Mynewtask'),
    path('edit_task/',views.EditTaskView,name='edit_task'),
]

sales/api/views.py
from rest_framework.views import APIView
from django.contrib.auth.models import User,Group
from rest_framework.response import Response
from sales.models import *
from membership.models import *
from tech.models import *
import datetime
from django.db.models import Prefetch
from .serializers import *
from django.db.models import Q

class GetMyNewLeads(APIView):
    def get(self,request):
        leads = Lead.objects.filter(assignedTo=self.request.user.salesexecutive,lead_status='is_successfull_lead').order_by('-date')
        serializer = LeadSerializer(leads,many=True)
        return Response({'Leads':serializer.data})

class GetMyNewLeadsDateWise(APIView):
    def post(self,request,*args,**kwargs):
        date = request.data['date']
        date = datetime.datetime.strptime(date,'%Y-%m-%d')
        date_wise_leads = Lead.objects.filter(assignedTo=self.request.user.salesexecutive,date__date=date.date()).order_by('-date')
        leadsSerializer = LeadSerializer(date_wise_leads,many=True)
        context = {'leads':leadsSerializer.data,'date':str(main_date)}
        return Response(context)

class GiveLeadFeedBack(APIView):
    def post(self,request,*args,**kwargs):
        my_profile = self.request.user.salesexecutive
        data = request.data
        lead_id = data['lead_id']
        demo = data['demo']
        executiveId = data['nextCall']
        furtherCall = data['furtherCall']
        nextCallDate = data['nextCallDate']
        demoDate = data['demoDate']

        try:
            nextCallDate = nextCallDate.strip('"') 
            nextCallDate = datetime.datetime.strptime(nextCallDate,'%Y-%m-%d %H:%M')
        except:
            nextCallDate = None        
        try:
            demoDate = demoDate.strip('"') 
            demoDate = datetime.datetime.strptime(demoDate,'%Y-%m-%d %H:%M')
        except:
            demoDate = None
        try:
            lead = Lead.objects.get(id=lead_id)
            lead.lead_status = 'worked_lead'
            lead.save()
        except Lead.DoesNotExist:
            return Response('Incorrect lead id ')

        feedback = FeedBack(by=my_profile,typeFeedBack=FeedBack.objects.filter(lead=lead_id).count()+1,lead=lead,rating = data['rating'],notes = data['notes'],
                            Cource=data['cource'],instituteType=data['instituteType'],State=data['State'],city=data['city'],
                            callrecording=data['audioUrl'],feedback=data['feedback'],priceQuoted=data['priceQuoted'])

        if data['Is_wrongLead'] == 'false':
            feedback.Is_wrongLead = False
        else:
            feedback.Is_wrongLead = True
            
        if furtherCall == 'true':
            feedback.furtherCall = True
        else:
            feedback.furtherCall = False

        
        if executiveId == 'None':
            feedback.nextCall = None
        else:
            NextCallerUser = SalesExecutive.objects.get(id=executiveId)
            feedback.nextCall = NextCallerUser
            DemoFeedback_And_LeadFeedback_Notifications.objects.create(notification_user=NextCallerUser,
            sender_user=my_profile,notification_type='LeadFeedbackNotification',lead=lead,
            massage = f"Today is your Feedback schedule of this {lead.personName} lead So remember This", is_FirstTime=True ,nextDate=nextCallDate,datetime=datetime.datetime.now())
        
        if demo == 'true':
            feedback.demo = True
            DemoFeedback_And_LeadFeedback_Notifications.objects.create(notification_user=my_profile,
            sender_user=my_profile,notification_type='DemoNotification',lead=lead,
            massage = f"Today is your demo schedule of this {lead.personName} lead So remember This", is_FirstTime=True ,nextDate=demoDate,datetime=datetime.datetime.now())
        else:
            feedback.demo = False

        feedback.demoDate = demoDate        
        feedback.nextCallDate = nextCallDate
        feedback.save()
        context = {'status':'Saved','message':'Feedback saved'}
        return Response(context)

class FindTypeFeedBack(APIView):
    def post(self,request,*args,**kwargs):
        my_profile = self.request.user.salesexecutive
        data = request.data
        lead_id = data['lead_id']
        lead = Lead.objects.get(id=lead_id)
        feedback = FeedBack.objects.filter(lead=lead)
        feedback_length = len(feedback)
        typeFeedBack = feedback_length + 1
        context = {'typeFeedback':typeFeedBack}
        return Response(context)

class GetAllSalesExecutives(APIView):
    def get(self,request):
        sales_people = SalesExecutive.objects.all()
        sales_list = []
        for sp in sales_people:
            sp_dict = {'id':sp.id,'name':sp.name}
            sales_list.append(sp_dict)
        context = {'salesPeople':sales_list}
        return Response(context)

class GetWorkedLeadsApi(APIView):
    def get(self,request):
        leads = Lead.objects.filter(assignedTo=self.request.user.salesexecutive,lead_status='worked_lead').order_by('-date')
        serializer = LeadSerializer(leads,many=True)
        return Response({'Leads':serializer.data})

class GetFeedbackOrDemos_A_specificLeadWiseApi(APIView):
    def post(self,request,*args,**kwargs):
        lead_id = request.data['lead_id']
        feedbackes = FeedBack.objects.filter(lead=lead_id)
        demos = DemoFeedback.objects.filter(lead=lead_id)
        feedbackserializer = FeedBackSerializer(feedbackes,many=True)
        demosserializer = DemoFeedbackSerializer(demos,many=True)
        context = {'feedbacks': feedbackserializer.data,'demosfeedbackes':demosserializer.data}
        return Response(context)

class GiveDemoFeedBackApi(APIView):
    def post(self,request):
        data = request.data
        lead_id = data['lead_id']
        my_profile = self.request.user.salesexecutive
        lead = Lead.objects.get(id=lead_id)
        DemoNextUser = data['demo_nextCall']
        DemoNextDate = data['demo_nextCallDate']
        demofeedback = DemoFeedback(typedemo=DemoFeedback.objects.filter(lead=lead_id).count()+1, by=my_profile, lead=lead,
                                    datetime=datetime.datetime.now(),
                                    demo_rating=data['demo_rating'],
                                    extra_notes=data['extra_notes'],
                                    demo_feedback=data['demo_feedback'],
                                    price_quoted=data['price_quoted'],
                                    callrecording=data['audioUrl'])
        if DemoNextDate == 'None':
            demofeedback.demo_nextCallDate = None
            DemoNextDate = None
        else:
            demofeedback.demo_nextCallDate = DemoNextDate
        if DemoNextUser == 'None':
            demofeedback.demo_nextCall = None
        else:
            nextcaller = SalesExecutive.objects.get(id=DemoNextUser)
            demofeedback.demo_nextCall = nextcaller
            DemoFeedback_And_LeadFeedback_Notifications.objects.create(notification_user=nextcaller,sender_user=my_profile,notification_type='DemoNotification',lead=lead,
            massage = f"Today is your Demo schedule of this {lead.personName} lead So remember This",is_FirstTime = True,nextDate=DemoNextDate,datetime=datetime.datetime.now())
        demofeedback.save()
        return Response({'status':'Saved','message':'Demo saved'})

class GetMyAssignedLeadsAPI(APIView):
    def get(self,request):
        assignedLeadss = Lead.objects.filter(Q(Q(Q(feeback_lead__nextCall=request.user.salesexecutive) | Q(demo_lead__demo_nextCall=request.user.salesexecutive)) & Q(Q(lead_status='worked_lead') | Q(lead_status='is_successfull_lead'))) & ~Q(Q(feeback_lead__by=request.user.salesexecutive) | Q(demo_lead__by=request.user.salesexecutive))).order_by('-feeback_lead__time')
        serializer = LeadSerializer(assignedLeadss,many=True)
        return Response(serializer.data)    
        
class GetSpecificLeadAndFeedbackAPI(APIView):
    def post(self,request):
        feedback_id = request.data['feedback_id']
        if feedback_id == 'None':
            feedback_id = None
        specific_lead= Lead.objects.get(id=request.data['lead_id'])
        leadserializer = LeadSerializer(specific_lead)
        try:
            specific_feedback = FeedBack.objects.get(id=feedback_id)
            feedbackserializer =  FeedBackSerializer(specific_feedback)
            context = {'lead':leadserializer.data,'feedback':feedbackserializer.data}
            return Response(context)
        except FeedBack.DoesNotExist:
            return Response({'lead':leadserializer.data})
        
class SendMessageToUserAPI(APIView):
    def get(self,request):
        leads = None
        users = SalesExecutive.objects.prefetch_related('lead_assign').all()
        for i in users:
            if i.lead_assign.filter(assignedTo=self.request.user.salesexecutive).exists():
                leads = i.lead_assign.filter(assignedTo=self.request.user.salesexecutive).order_by('-date')
                break
        serializer = LeadSerializer(leads,many=True)
        Userserializer = SalesExecutiveSerializer(users,many=True)
        context = {'AllUsers':Userserializer.data,'leads':serializer.data}
        return Response(context)
    
    def post(self,request):
        data = request.data
        lead_id = data['lead_id']
        Lead_Feedback_Id = data['feedback_id']

        if Lead_Feedback_Id == 'None':
            Lead_Feedback_Id = None
        else:
            Lead_Feedback_Id = FeedBack.objects.get(id=Lead_Feedback_Id) 
        if lead_id == 'None':
            lead_id = None
        else:
            lead_id = Lead.objects.get(id=lead_id)

        Massages.objects.create(senderId=self.request.user.salesexecutive,reciverId=SalesExecutive.objects.get(id=data['reciver']),lead=lead_id,feedback=Lead_Feedback_Id,massage=data['message'],datetime=datetime.datetime.now())
        

sales/templates/sales/AddSuccessfullyLead.html
{% extends 'sales/base.html'%}
{% block title %}Add successfully lead{% endblock title %}
{% block body %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<style>
  .maincls {
    background-color: #6c757dad;
    border-radius: 2ch;
    width: 600px;
  }

  .subcls {
    margin-top: 20px;
  }

  #feedbackbtnid {
    margin-left: 200px;
    margin-bottom: 10px;
  }
</style>
<h1 style="text-align: center; color: black;">Add successfull Lead</h1>
<div class="container maincls " style="margin-top: 40px;" id="all_leads">
  <div class="div subcls " style="margin-left: 30px;">
    <form action="{% url 'sales:add_comfirmLead' %}" method="POST">
      {% csrf_token %}
      <div class="form-row" style="width: 500px;">
        <div class="form-group">
          <label for="inputPassword4">successfully Lead *</label>
          <select name="comfirmlead" class="form-control">
            <option value="" selected>Choose...</option>
            {% for lead in leads %}
            <option value="{{lead.id}}">{{lead.personName}}</option>
            {% endfor %}
          </select>
        </div>
        <div class="form-group" id="forcheck">
          <label for="inputPassword4">Decided Price *</label>
          <input type="text" class="form-control" name="decidedPrice" required placeholder="type price">
        </div>
        <div class="form-group" id="forcheck">
          <label for="inputPassword4">Extra requirments</label>
          <input type="text" class="form-control" name="extrarequirments" placeholder="type requirments">
        </div>
      </div>
      <button type="submit" id="feedbackbtnid" class="btn btn-primary">Add Lead</button>
    </form>
  </div>
</div>
{% endblock body %}

sales/templates/sales/DemoCreating.html
{% extends 'sales/base.html'%}
{% load humanize %}
{% block title %}Create demo {% endblock title %}
{% block body %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <style>
    body {
      /* background-image: url("https://www.teahub.io/photos/full/313-3132029_linkedin-wallpaper-wallpapersafari-background-image-for-form-in.jpg"); */
      background-image: url("https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__340.jpg");
    }

    .maincls {
      background-color: wheat;
      border-radius: 5ch;
    }

    .subcls {
      margin-top: 20px;
    }

    .formfield {
      margin: 10px;
    }
    #feedbackbtnid {
      margin-left: 500px;
      margin-bottom: 10px;
    }
  </style>
  <h1 style="text-align: center; color: white;">Create Demo {{typedemo|ordinal}} Time</h1>
  <div class="container maincls" style=" margin-top: 40px;" id="all_leads">
    <div class="div subcls">
      <form action="{% url 'sales:demo_creating' %}" method="POST">
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="inputPassword4">Demo rating *</label>
            <input type="number" class="form-control" name="demo_rating" required placeholder="Enter rating">
          </div>
          <div class="form-group col-md-6">
            <label for="inputPassword4">Demo feedback *</label>
            <select name="demo_feedback" required class="form-control">
              <option value="" selected>Choose...</option>
              <option value="Invalid Number">Invalid Number</option>
              <option value="Call not recieved">Call not recieved</option>
              <option value="Not Responding">Not Responding</option>
              <option value="Not Interested">Not Interested</option>
              <option value="Not Reachable">Not Reachable</option>
              <option value="Interested">Interested</option>
              <option value="Will update when needed">Will update when needed</option>
              <option value="Call back">Call back</option>
              <option value="call busy">call busy</option>
              <option value="switched off">switched off</option>
              <option value="using other application">using other application</option>
              <option value="cut call">cut call</option>
              <option value="Incoming call not available">Incoming call not available</option>
            </select>
          </div>
          <div class="form-group col-md-6">
            <label for="inputPassword4">Extra notes</label>
            <input type="text" class="form-control" name="extra_notes" placeholder="Enter feedback">
          </div>
          <div class="form-group col-md-6">
            <label for="inputPassword4">Price quoted</label>
            <input type="text" class="form-control" name="price_quoted" placeholder="Enter feedback">
          </div>
          <div class="form-group col-md-6">
            <label for="inputPassword4">Assign DemoNextCall</label>
            <select name="demo_nextCall" class="form-control">
              <option value="" selected>Choose...</option>
              {% for user in SalesExecutiveUser %}
              <option value="{{user.id}}">{{user.executiveUser}} {{user.typeExecutive}}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group col-md-6">
            <label for="inputPassword4">Next CallDate</label>
            <input type="datetime-local" class="form-control" name="demo_nextCallDate" placeholder="Enter Date">
          </div>
        </div>
        {% if request.GET.lead_id %}
        <input type="hidden" name="lead_id" value="{{request.GET.lead_id}}">
        {% endif %}
        <button type="submit" id="feedbackbtnid" class="btn btn-primary">Submit DemoFeedback</button>
      </form>
    </div>
  </div>
  {% endblock body %}

sales/templates/sales/MassageForm.html
{% extends 'sales/base.html'%}
{% block title %}Send message{% endblock title %}
{% block body %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<style>
  .maincls {
    background-color: #6c757dad;
    border-radius: 2ch;
    width: 600px;
  }

  .subcls {
    margin-top: 20px;
  }

  #feedbackbtnid {
    margin-left: 200px;
    margin-bottom: 10px;
  }
</style>
<h1 style="text-align: center; color: black;">Sending Message</h1>
<div class="container maincls " style="margin-top: 40px;" id="all_leads">
  <div class="div subcls " style="margin-left: 30px;">
    <form action="{% url 'sales:Sendmassage' %}" method="POST">
      {% csrf_token %}
      <div class="form-row" style="width: 500px;">
        <div class="form-group">
          <label for="inputPassword4">To *</label>
          <select name="reciver" class="form-control" required>
            <option value="" selected>Choose...</option>
            {% for user in SalesExecutiveUser %}
            <option value="{{user.id}}">{{user.executiveUser}} {{user.typeExecutive}}</option>
            {% endfor %}
          </select>
        </div>
        <div class="form-group" id="forcheck">
          <label for="inputPassword4">Message *</label>
          <input type="text" class="form-control" required name="massage" required placeholder="type message">
        </div>
        <div class="form-group">
          <label for="inputPassword4">Lead</label>
          <select name="sendinglead" id="leadfeedbacksalecttag" onchange="slectinglead()" class="form-control">
            <option value="" selected>Choose...</option>
            {% for lead in leads %}
            <option value="{{lead.id}}">{{lead.personName}}</option>
            {% endfor %}
          </select>
        </div>
        <div class="form-group" id="leadfeedbackdiv">
          <label for="inputPassword4">Lead Feedback</label>
          <select name="feedback" id="feedbacksalectTag" class="form-control">
            <option value selected>Choose...</option>
          </select>
        </div>
      </div>
      <button type="submit" id="feedbackbtnid" class="btn btn-primary">Send Massage</button>
    </form>
  </div>
</div>
<script>
  function slectinglead() {
    var selectBox = document.getElementById("leadfeedbacksalecttag");
    selected_lead_id = selectBox.options[selectBox.selectedIndex].value
    document.querySelectorAll('#feedbacksalectTag option').forEach(o => o.remove());
    $("#feedbacksalectTag").append('<option value selected>Choose..</option>')
    $.ajax(
      {
        type: "GET",
        url: "/sales/getting_feedbackes_leadwise_by_ajex",
        data: {
          Selected_lead_id: selected_lead_id
        },
        success: function (data) {
          for (i = 0; i < data.length; i++) {
            $("#feedbacksalectTag").append('<option value="' + data[i]["id"] + '">' + data[i]["typeFeedBack"] + '</option>')
          }
        }
      });
  }
</script>
{% endblock body %}

sales/templates/sales/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

  <style>
    #intro-example {
      height: 400px;
    }

    .tagnameclr {
      color: white;
      font-size: 3ch;
      margin-left: 50px;
    }

    @media (min-width: 992px) {
      #intro-example {
        height: 600px;
      }
    }

    .maincls {
      background-color: #6c757dad;
      border-radius: 2ch;
      width: 600px;
    }

    .subcls {
      margin-top: 20px;
    }
  </style>
</head>

<body>
  <header>
    <nav class="navbar navbar-dark bg-primary" style="background-color: 2e6da4">
      <a class="navbar-brand tagnameclr"
        style="font-size: 260%; color: black; font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif"
        href="/">Bodhi Ai</a>
      <div class="collapse navbar-collapse" style="margin-top: 8px;" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% if request.user.salesexecutive %}
          <a class="nav-item nav-link tagnameclr" href="/sales/Get_my_new_leads">New Leads</a>
          <a class="nav-item nav-link tagnameclr" href="/sales/Get_my_worked_leads">Worked Leads</a>
          <a class="nav-item nav-link tagnameclr" href="/sales/Get_my_assigned_leads">Assigned Leads</a>
          <a class="nav-item nav-link tagnameclr" href="/sales/Specific_person_successfullLeads/">Successfully Leads</a>
          <a class="nav-item nav-link tagnameclr" href="/sales/Sendmassage">Message</a>
          <a class="nav-item nav-link tagnameclr" href="/sales/messagesInbox/">Inbox</a>
          {% else %}
          <a class="nav-item nav-link tagnameclr" href="/tech/Get_Mynewtask/">New task</a>
          {% endif %}
          <a href="/sales/logout">
            <button class="tagnameclr" style="background-color:whitesmoke; color: black;border-radius: 1ch; ">
              Logout
            </button>
          </a>
        </div>
      </div>
    </nav>
  </header>
  {% block body %} {% endblock body %}
  {% if messages %}
  <div class="container" style="height: 200px; position: fixed;top:500px; left: 200px; right: 200px;">
    <div class="div"
      style="margin: 0; position: absolute; top: 50%; left: 50%; -ms-transform: translate(-50%, -50%); transform: translate(-50%, -50%);">
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>{{ message.tags }}!</strong> {{ message }}.
      </div>
      {% endfor %}
    </div>
  </div>
  {% endif %}
</body>

</html>